### ISSUE TITLE
MASTERCARD PARAMETER FILE

### ISSUE THREAD

**Issue by charisad** [adelosa/cardutil#8] opened 2022-06-16 08:30 UTC
How do I determine DE93 from Parameter file using mci_ipm_param_to_csv.

**Comment by adelosa** [comment] 2022-06-16 12:35
I have not mapped out all the config in the IPM Param files so not sure the specific table that contains the DE field mapping to convert to CSV. 
If you know what table, you can provide your own mapping via config. I don't have the MasterCard manuals to hand to check this.

**Comment by charisad** [comment] 2022-06-16 14:46
Okay, I found the tables I want  IP0040T1  and IP0075T1. Can you assist on how to use the mci_ipm_param_to_csv? Always getting this error -- requested 4 bytes, got 0 -- exiting. Kindly assist

**Comment by adelosa** [comment] 2022-06-21 00:12
I will look at this when I have some time. I am available for paid engagements if your request is urgent. Please contact me via email for more details on costs to go down this path. Otherwise, please refrain from posting reminders here. Thanks.

**Comment by adelosa** [comment] 2022-07-02 02:04
Hi there,
There is not enough information for me to work out what the issue is. The 2 tables you mentioned have config, but I have not updated them for some time. 
I am going to add a debug option to the command line utilities so that I can diagnose issues with files without having the files sent to me, but this will take me a little bit of time to put together. It will be available in the next release.
I'll let you know..

**Comment by charisad** [comment] 2022-10-17 10:08
Hi @adelosa can you please share a sample config file for the mci_ipm_param_to_csv --config parameter

**Comment by adelosa** [comment] 2022-10-17 12:02
Config file documentation: https://cardutil.readthedocs.io/en/latest/cli.html#config-file and https://cardutil.readthedocs.io/en/latest/api.html#mci-parameter-tables
Provided default config file: https://github.com/adelosa/cardutil/blob/master/cardutil/config.py
Let me know if you need more details. Please consider contributing your new config file back to the project by attaching it to this issue. I will then update the default config.

**Comment by charisad** [comment] 2022-10-17 12:42
Hi Anthony,

Thanks, I have found the config file, I will attach the updated config file
to the issue soon.

Regards,

Collins Baffour.

**Comment by charisad** [comment] 2022-10-18 11:54
Hi Anthony now everything is working fine, can the echo be turned off for mci_ipm_param_to_csv?

**Comment by adelosa** [comment] 2022-10-18 20:59
I don't know what you mean. Can you provide details of what command paeans and the output you are receiving so I can understand the issue.

**Comment by charisad** [comment] 2022-10-21 07:35
This is what I mean when you execute the command below, I don't want the tables to be printed in the console as in the image below:

mci_ipm_param_to_csv --in-encoding latin1 T168OLD --config cardutil.json IP0040T1

![image](https://user-images.githubusercontent.com/23213757/197139261-f2d2c20d-9e08-44a1-a8cd-6e9f860d89a5.png)

**Comment by adelosa** [comment] 2022-10-21 08:27
What is the contents of cardutil.json?

**Comment by charisad** [comment] 2022-10-21 09:14
The updated config file I sent to you

**Comment by adelosa** [comment] 2022-10-22 01:05
OK great - I missed the files you added to GitHub.. Thanks for this. I am adding this to the default config. I have also removed the print of the tables from param reader so you should not see this list unless you are using debug mode.
I will be releasing a new version shortly including the debug, config updates and above print remove.

**Comment by charisad** [comment] 2022-10-22 10:59
Awesome, thanks!

**Comment by adelosa** [comment] 2022-10-27 11:17
Closing as resolved.

**Closed by adelosa** 2022-10-27 11:17 UTC
Labels: data issue
